### ISSUE TITLE
Fix Favicon

### ISSUE THREAD

**Issue by 0xTim** [brokenhandsio/are-we-server-yet#6]
It's not working in Safari - we should try and align it. I've used https://realfavicongenerator.net before which has worked well

**Comment by ptoffy** [comment]
It's working for me! Maybe this is resolved?

![Screenshot 2023-08-24 at 15 41 15](https://github.com/brokenhandsio/are-we-server-yet/assets/69189821/59065e20-2aeb-480c-a639-50730546f6e0)

**Comment by 0xTim** [comment]
Yep seems to be fine
